### ISSUE TITLE
En TratamientoDeImagen.py te falta importar pixelRGB2LAB

### ISSUE THREAD

**Issue by joseFranciscoDiez** [apj0007/PrawnView#60]

**Comment by apj0007** [comment]
`def base1(num):
        valorEnBase255 = num
        valorEnBase1 = (valorEnBase255/255)*1
        return valorEnBase1

    '''
    Función para pasar un pixel de RGB a CIELAB

    CIELAB es más apropiado para hacer diferencia de colores
    '''
   @classmethod
    def pixelRGB2LAB(pixel):
        r,g,b = pixel # pixel es una lista con 3 valores, los puedo guardar en 3 variables asi
        rBase1 = base1(r)
        gBase1 = base1(g)
        bBase1 = base1(b)

`
